
--Insert Cliente

INSERT INTO "CLIENTE" (NOMBRE, TELEFONO, CORREOELECTRONICO, RUBRO, DIRECCION, CANTIDADTRABAJADORES) VALUES ('Carmen Rojas', '227768131', 'carmen.rojas@gmail.com', 'Agricola', 'Camino el agricola 2530', '2600');
INSERT INTO "CLIENTE" (NOMBRE, TELEFONO, CORREOELECTRONICO, RUBRO, DIRECCION, CANTIDADTRABAJADORES) VALUES ('Tomas Reyes', '226712012', 'tomas.reyes@hotmail.com', 'Construcción', 'Alameda 3839', '540');
INSERT INTO "CLIENTE" (NOMBRE, TELEFONO, CORREOELECTRONICO, RUBRO, DIRECCION, CANTIDADTRABAJADORES) VALUES ('Carlotta Maldonado', '228881234', 'c.maldonado@gmail.com', 'Alimentación', 'Agustinas 2424', '30');
INSERT INTO "CLIENTE" (NOMBRE, TELEFONO, CORREOELECTRONICO, RUBRO, DIRECCION, CANTIDADTRABAJADORES) VALUES ('Juan Pedro Retamal', '227776621', 'jpret@gmail.com', 'Industrial', 'Carrera 233', '380');
INSERT INTO "CLIENTE" (NOMBRE, TELEFONO, CORREOELECTRONICO, RUBRO, DIRECCION, CANTIDADTRABAJADORES) VALUES ('Camila Perez', '222345698', 'cami@hotmail.com', 'Turistico', 'Villarrica 9898', '496');

--Insert Empleado

INSERT INTO "EMPLEADO" (NOMBRE, ESPECIALIDAD) VALUES ('Catalina Aedo', 'Ingeniera en Procesos');
INSERT INTO "EMPLEADO" (NOMBRE, ESPECIALIDAD) VALUES ('Ulises Santana', 'Ingeniero en prevención de riesgos');
INSERT INTO "EMPLEADO" (NOMBRE, ESPECIALIDAD) VALUES ('Federico Alegria', 'Ingeniero en Seguridad');
INSERT INTO "EMPLEADO" (NOMBRE, ESPECIALIDAD) VALUES ('Laura Paredes', 'Ingeniera Industrial');

-- Insert Visitas

INSERT INTO VISITAS (DIRECCION, CIUDAD, FECHA, RESUMEN, OBSERVACIONES, CLIENTE_ID_CLIENTE, EMPLEADO_ID_EMPLEADO) VALUES ('Camino el agricola 2530', 'Santiago', '12-04-2020', 'Visita de rutina', 'Buen manejo de la seguridad de los trabajadores', 1, 1);
INSERT INTO VISITAS (DIRECCION, CIUDAD, FECHA, RESUMEN, OBSERVACIONES, CLIENTE_ID_CLIENTE, EMPLEADO_ID_EMPLEADO) VALUES ('Villarrica 9898', 'Santiago', '10-06-2020', 'Visita mensual', 'Pesima seguridad en las instalaciones de la empresa', 2, 3);
INSERT INTO VISITAS (DIRECCION, CIUDAD, FECHA, RESUMEN, OBSERVACIONES, CLIENTE_ID_CLIENTE, EMPLEADO_ID_EMPLEADO) VALUES ('Carrera 233', 'Santiago', '15-01-2020', 'Visita de asesoria especial', 'Se debe hacer seguimiento',1 , 2);

-- Insert Asesorias

INSERT INTO ASESORIAS(DETALLE, GESTION, PROPUESTAS, FECHA, ESPECIAL, VISITAS_ID_VISITA) VALUES('Visita planta 2', 'lograda' , 'implementar señaleticas y mejor seguridad', '02-06-2020', 'si',1);
INSERT INTO ASESORIAS(DETALLE, GESTION, PROPUESTAS, FECHA, ESPECIAL, VISITAS_ID_VISITA) VALUES('Visita planta 3', 'lograda' , 'implementar señaleticas y mejor seguridad', '02-06-2020', 'no',2);
INSERT INTO ASESORIAS(DETALLE, GESTION, PROPUESTAS, FECHA, ESPECIAL, VISITAS_ID_VISITA) VALUES('Visita planta 4', 'lograda' , 'implementar señaleticas y mejor seguridad', '02-06-2020', 'si',2);
INSERT INTO ASESORIAS(DETALLE, GESTION, PROPUESTAS, FECHA, ESPECIAL, VISITAS_ID_VISITA) VALUES('Visita planta 5', 'lograda' , 'implementar señaleticas y mejor seguridad', '02-06-2020', 'no',1);

--Insert Pagos
INSERT INTO PAGOS(MESANIO, MONTOREGULAR, MONTOADICIONALES, CLIENTE_ID_CLIENTE) VALUES('02-2020', 20, 23,1);
INSERT INTO PAGOS(MESANIO, MONTOREGULAR, MONTOADICIONALES, CLIENTE_ID_CLIENTE) VALUES('03-2020', 20, 23,4);
INSERT INTO PAGOS(MESANIO, MONTOREGULAR, MONTOADICIONALES, CLIENTE_ID_CLIENTE) VALUES('06-2020', 20, 23,3);
INSERT INTO PAGOS(MESANIO, MONTOREGULAR, MONTOADICIONALES, CLIENTE_ID_CLIENTE) VALUES('07-2020', 20, 23,2);

--Insert Accidente

INSERT INTO ACCIDENTES(FECHA, HORA, SUCESO, LUGAR, CLIENTE_ID_CLIENTE) VALUES('02-04-2020', '23:30', 'quemaduras leves grado 23232', 'Santiago',1);
INSERT INTO ACCIDENTES(FECHA, HORA, SUCESO, LUGAR, CLIENTE_ID_CLIENTE) VALUES('02-06-2020', '22:15', 'quemadura grado 23', 'Quilicura',2);
INSERT INTO ACCIDENTES(FECHA, HORA, SUCESO, LUGAR, CLIENTE_ID_CLIENTE) VALUES('12-05-2020', '21:20', 'quemaduras grave grado 2343253', 'puente alto',3);
INSERT INTO ACCIDENTES(FECHA, HORA, SUCESO, LUGAR, CLIENTE_ID_CLIENTE) VALUES('06-06-2020', '20:20', 'se pincho el dedo', 'Las Condes',4);

--Insert Capacitacion

insert into CAPACITACIONES(FECHA, HORA, NUMASISTENTES, VISITAS_ID_VISITA) VALUES ('10-2020','12:00', 23,1);
insert into CAPACITACIONES(FECHA, HORA, NUMASISTENTES, VISITAS_ID_VISITA) VALUES ('04-2020','11:00', 54,2);
insert into CAPACITACIONES(FECHA, HORA, NUMASISTENTES, VISITAS_ID_VISITA) VALUES ('11-2020','10:00', 23,3);
