
--Insertar uno por uno estos triggers
CREATE or replace TRIGGER ACCIDENTES_TRG 
BEFORE INSERT ON ACCIDENTES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ACCIDENTE IS NULL THEN
      SELECT ACCIDENTES_SEQ.NEXTVAL INTO :NEW.ID_ACCIDENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
--Insertar uno por uno estos triggers

CREATE or replace TRIGGER ASESORIAS_TRG 
BEFORE INSERT ON ASESORIAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ASESORIA IS NULL THEN
      SELECT ASESORIAS_SEQ.NEXTVAL INTO :NEW.ID_ASESORIA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

--Insertar uno por uno estos triggers
CREATE or replace TRIGGER CAPACITACIONES_TRG 
BEFORE INSERT ON CAPACITACIONES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CAPACITACION IS NULL THEN
      SELECT CAPACITACIONES_SEQ.NEXTVAL INTO :NEW.ID_CAPACITACION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
--Insertar uno por uno estos triggers

CREATE or replace TRIGGER CHEQUEO_TRG 
BEFORE INSERT ON CHEQUEO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CHEQUEO IS NULL THEN
      SELECT CHEQUEO_SEQ.NEXTVAL INTO :NEW.ID_CHEQUEO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

--Insertar uno por uno estos triggers

CREATE or replace TRIGGER CLIENTE_TRG 
BEFORE INSERT ON CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CLIENTE IS NULL THEN
      SELECT CLIENTE_SEQ.NEXTVAL INTO :NEW.ID_CLIENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
--Insertar uno por uno estos triggers

CREATE or replace TRIGGER EMPLEADO_TRG 
BEFORE INSERT ON EMPLEADO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMPLEADO IS NULL THEN
      SELECT EMPLEADO_SEQ.NEXTVAL INTO :NEW.ID_EMPLEADO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

--Insertar uno por uno estos triggers
CREATE or replace TRIGGER MEJORAS_TRG 
BEFORE INSERT ON MEJORAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_MEJORA IS NULL THEN
      SELECT MEJORAS_SEQ.NEXTVAL INTO :NEW.ID_MEJORA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
--Insertar uno por uno estos triggers

CREATE or replace TRIGGER PAGOS_TRG 
BEFORE INSERT ON PAGOS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PAGO IS NULL THEN
      SELECT PAGOS_SEQ.NEXTVAL INTO :NEW.ID_PAGO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

--Insertar uno por uno estos triggers
CREATE or replace TRIGGER VISITAS_TRG 
BEFORE INSERT ON VISITAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_VISITA IS NULL THEN
      SELECT VISITAS_SEQ.NEXTVAL INTO :NEW.ID_VISITA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

-- SI ESTO NO FUNCIIONA FAVOR DE CREAR SECUENCIAS A MANO
